### ISSUE TITLE
LNS "Purchase" button stays disabled

### ISSUE THREAD

**Issue by jagerman** [oxen-io/oxen-electron-gui-wallet#261] opened 2021-03-15 14:43 UTC
I'm not exactly sure what triggers this but a user reported (and I verified, on an empty wallet) that when you fill out the LNS details for a lokinet domain the Purchase button stays disabled.  In my case it might have been from lack of funds, but in the reported case the user had enough available to buy + pay the tx fee.

**Comment by darcys22** [comment] 2021-07-07 00:04
The "lack of funds" logic was enough for ONS name + 1 oxen buffer. We reduced the 1 oxen buffer to 0.1 in this PR recently #284 

Likely this was the cause. Happened to a couple people.

Closing and will reopen if this happens again

**Closed by darcys22** 2021-07-07 00:04 UTC

**Comment by VityaSchel** [comment] 2024-01-26 18:24
I'm still having the same issue (v1.8.1)
<img width="892" alt="image" src="https://github.com/oxen-io/oxen-electron-gui-wallet/assets/59040542/1b162156-99b7-423e-aa20-a8ec449755cf">
<img width="899" alt="image" src="https://github.com/oxen-io/oxen-electron-gui-wallet/assets/59040542/3cc3aeaf-18bc-47b9-b630-9a59ad6f7d65">
![image](https://github.com/oxen-io/oxen-electron-gui-wallet/assets/59040542/02f5be1c-d83d-4a5c-98b3-38162011ac46)

**Comment by VityaSchel** [comment] 2024-01-26 18:27
I think it's related to unlocked balance being zero but as a new user to OXEN I have no idea what unlocked balance is haha
maybe add a hint that the received oxen may be spent after some time? because now it seems like i have two separate balances and I have to do something on my behalf to unlock my money
